### ISSUE TITLE
Error while running uglify using 1.0.3

### ISSUE THREAD

**Issue by sauravshah** [sbt/sbt-uglify#15]
[info] Optimizing 1 JavaScript(s) with Uglify
[error] util.error: Use console.error instead
[error] ERROR: Source map doesn't work with input from STDIN
[info]
[trace] Stack trace suppressed: run last dashboard/web-assets:mappings for the full output.
[error] (dashboard/web-assets:mappings) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: util.error: Use console.error instead
[error] ERROR: Source map doesn't work with input from STDIN
[error] Total time: 14 s, completed Nov 17, 2015 2:33:54 PM
[quality-service] $ last dashboard/web-assets:mappings
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: util.error: Use console.error instead
ERROR: Source map doesn't work with input from STDIN

	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] (dashboard/web-assets:mappings) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: util.error: Use console.error instead
[error] ERROR: Source map doesn't work with input from STDIN

**Comment by weickmanna** [comment]
I experienced the exact same error message. For me, the fix was to move my JavaScript files from the public folder into the app/assets folder.
